require:
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - '**/db/schema.rb'

  TargetRubyVersion: 3.1

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - 'app/lib/verified_address.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - 'app/lib/verified_address.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Output:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'config/application.rb'

Style/Documentation:
  Enabled: false
