# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/researchers' do
  let(:valid_attributes) { attributes_for(:researcher) }

  let(:invalid_attributes) { attributes_for(:researcher, university_profile_url: '') }

  describe 'GET /show' do
    it 'renders a successful response' do
      researcher = create(:researcher)
      get researcher_url(researcher)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_researcher_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      researcher = create(:researcher)
      get edit_researcher_url(researcher)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Researcher' do
        expect do
          post researchers_url, params: { researcher: valid_attributes }
        end.to change(Researcher, :count).by(1)
      end

      it 'redirects to the created researcher' do
        post researchers_url, params: { researcher: valid_attributes }
        expect(response).to redirect_to(researcher_url(Researcher.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Researcher' do
        expect do
          post researchers_url, params: { researcher: invalid_attributes }
        end.not_to change(Researcher, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post researchers_url, params: { researcher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested researcher' do
        researcher = create(:researcher)
        patch researcher_url(researcher), params: { researcher: new_attributes }
        researcher.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the researcher' do
        researcher = create(:researcher)
        patch researcher_url(researcher), params: { researcher: new_attributes }
        researcher.reload
        expect(response).to redirect_to(researcher_url(researcher))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        researcher = create(:researcher)
        patch researcher_url(researcher), params: { researcher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested researcher' do
      researcher = create(:researcher)
      expect do
        delete researcher_url(researcher)
      end.to change(Researcher, :count).by(-1)
    end

    it 'redirects to the researchers list' do
      researcher = create(:researcher)
      delete researcher_url(researcher)
      expect(response).to redirect_to(researchers_url)
    end
  end
end
