# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/studies' do
  # This should return the minimal set of attributes required to create a valid
  # Study. As you add validations to Study, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Study.create! valid_attributes
      get studies_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      study = Study.create! valid_attributes
      get study_url(study)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_study_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      study = Study.create! valid_attributes
      get edit_study_url(study)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Study' do
        expect do
          post studies_url, params: { study: valid_attributes }
        end.to change(Study, :count).by(1)
      end

      it 'redirects to the created study' do
        post studies_url, params: { study: valid_attributes }
        expect(response).to redirect_to(study_url(Study.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Study' do
        expect do
          post studies_url, params: { study: invalid_attributes }
        end.not_to change(Study, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post studies_url, params: { study: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested study' do
        study = Study.create! valid_attributes
        patch study_url(study), params: { study: new_attributes }
        study.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the study' do
        study = Study.create! valid_attributes
        patch study_url(study), params: { study: new_attributes }
        study.reload
        expect(response).to redirect_to(study_url(study))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        study = Study.create! valid_attributes
        patch study_url(study), params: { study: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested study' do
      study = Study.create! valid_attributes
      expect do
        delete study_url(study)
      end.to change(Study, :count).by(-1)
    end

    it 'redirects to the studies list' do
      study = Study.create! valid_attributes
      delete study_url(study)
      expect(response).to redirect_to(studies_url)
    end
  end
end
