# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: sb-dev
  pool: 5

development:
  <<: *default
  database: sb-dev

test:
  <<: *default
  database: sb-test

production:
  <<: *default
  database: sb-prod
  username: ssstutterbuddy
  password: <%= ENV["SSSB_DATABASE_PASSWORD"] %>
